# Generated by Django 3.0.5 on 2020-04-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_short', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discord_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Discord')),
                ('steam_link', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Steam')),
                ('streamer_link', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stream URL')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_general_manager', models.BooleanField(default=False)),
                ('is_assistant_general_manager', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vese_app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Season')),
                ('start_date', models.DateField(verbose_name='Season Start')),
                ('end_date', models.DateField(verbose_name='Season End')),
                ('leagues', models.ManyToManyField(to='vese_app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_short', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Week')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vese_app.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_players', models.ManyToManyField(blank=True, related_name='away_players', to='vese_app.Player')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='vese_app.Team')),
                ('home_players', models.ManyToManyField(blank=True, related_name='home_players', to='vese_app.Player')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='vese_app.Team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vese_app.Week')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_winning_team', to='vese_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vese_app.Team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='game')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vese_app.Series')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winning_team', to='vese_app.Team')),
            ],
        ),
    ]
